### ISSUE TITLE
Feature Request/Clarification - Adding Show Players Outputs to Stream Screen

### ISSUE THREAD

**Issue by GarebearNF** [ardittristan/VTTStreamUtils#14]
I'm wondering if there is a way for a GM to use the Show Players function to display images or other content, and for it to appear on the stream screen for a preset amount of time. Is this something that just requires some custom configs, or would this be a full on feature addition?

Thanks!

**Comment by ardittristan** [comment]
Sorry, could you maybe elaborate on this `Show Players` function? I've never used it, or do you mean as a totally new functionality?

**Comment by GarebearNF** [comment]
Sure thing. I believe this is a core functionality that allows you to show journal entries or images to your players. Typically, when you open a journal entry, you have a Show Players option in the header. This creates a pop-up on the other players' screens to display the content triggered. I am wondering if it's possible to dedicate an area of the /stream view to facilitate these pop-ups, and maybe close them after a predetermined time period.
![image](https://user-images.githubusercontent.com/22135506/152664496-c6713799-cee6-4611-b96a-6adc4362a768.png)

**Comment by CasualTerror** [comment]
That is a function of another module called Stream View. It's pretty much a much have if you stream and a good companion to Stream Utils

**Comment by GarebearNF** [comment]
I do use both, but the StreamView is typically good when a stream is looking at the "table". If I want to simply do a scene without the table, and only cameras and images it would be great to simply chroma key in a pop up when I need to show a reference image. It's by no mean **unusable** as is, just what I believe to be a quality of life improvement for those that actually use the /stream view to stream games.

**Comment by ardittristan** [comment]
how's this version?

**Comment by ardittristan** [comment]
are you showing a journal or something else? I've only tested it with journals

**Comment by GarebearNF** [comment]
I was testing journals as well as images added via an image tag and the vanilla journal image. It looks like plain text from a journal, as well as images added by an image tag show until a new journal is shared. 

However, images in a journal using the image tab in the header of any given journal are not shown when shared. I also noticed in testing that certain journal modules are ignored in the call to the /stream view. I assume due to different journal calls within certain modules. 

As an example, Monk's Enhanced Journal is ignored while OneJournal shows as if vanilla.

**Comment by ardittristan** [comment]
- Images: fixed in next update
- OneJournal journals seem to work fine
- Monks Journal I'm working on fixing, also next update
- any other journal modules I should take a look at?

**Comment by GarebearNF** [comment]
Those are the ones that I am aware of. There is Custom Journal, but I think that only is a CSS module for journals.

Thank you for taking the time to tackle this!

**Comment by ardittristan** [comment]
Monks Journal seems like a lot of work to implement, so I'll push the images fix as a separate hotfix

**Comment by GarebearNF** [comment]
I just loaded up the hot fix, and it works great for vanilla journals. I did also remember that TidySheets has a function to show Actor portraits and tokens. I don't typically use it, but I tested it. 

It displays the image called, but as a full window (as if being shown in /game) but not in the window frame. 

Just something else to keep an eye out for.
